### ISSUE TITLE
How set Custom text for header and footer  

### ISSUE THREAD

**Issue by Pratiktarade** [ericschernoff/HTMLDoc#2]
I want to set Custom Text for header and footer but no such provision provided even
not mentioned in document how to set custom text . I Request to all please
suggest .. and do needful

Thanks and regard's

Pratik

**Comment by ericschernoff** [comment]
Hi Pratik,

I should extend the documentation to make this more clear, but you can utilize all of the HTML tags specified in the HTMLDoc guide here:  https://www.msweet.org/htmldoc/htmldoc.html

Specifically, I had a need recently where I needed to add custom footer text, and I used these tags in my HTML document:




I needed those footers on the first five pages but not on the last page, so I was able to place those tags before the five  tags, then a different  tag on the last page.  * I believe if I just had those once tags at the top, the footer would have been the same on each page. *

I will leave this issue active pending your questions and improvements to the docs on my part.

-Eric

**Comment by ericschernoff** [comment]
Pratik,

I have added a few notes to the documentation, specifically:

There are also several HTMLDOC-specific comment options detailed here: https://www.msweet.org/htmldoc/htmldoc.html#COMMENTS

Please use the get_htmldoc_command() method to retrieve an HTMLDOC command with your options for easy troubleshooting. If your HTML does not work with the HTMLDOC command, it will also not work with this module.

-Eric
